import pandas as pd
df1 = pd.read_csv("C:/Users/DAI.STUDENTSDC/Downloads/data1.csv")
df2 = pd.read_csv("C:/Users/DAI.STUDENTSDC/Downloads/data2.csv")
# df = pd.merge(df1, df2, how="cross")
# df = pd.merge(df1, df2, on="emp_id",how="outer")
# print(df1)
# print(df2)
# print(df)
m = pd.merge(df1,df2, on="emp_id", how="outer")
x=df1.groupby(["emp_location"])
x1=df1.groupby(["emp_location"]).count()
# print(x.groups)
# print(x1)
print(m)
print(m.drop_duplicates(subset=['emp_id']))